# Generated by Django 3.2.16 on 2023-02-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Togri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soz', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Xato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notogri', models.CharField(max_length=40)),
                ('stogri_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.togri')),
            ],
        ),
    ]
